services:
  - type: web
    name: online-job-portal-backend
    runtime: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/online-job-portal-0.0.1-SNAPSHOT.jar"
    env: 
      - key: JAVA_VERSION
        value: 17
    region: oregon
    plan: free
    branch: main
    repo: https://github.com/babysaranya7/my-fullstack-project
